In [1]:
import numpy as np
from numpy import linalg

################################################################################
# Function: idempotents                                                        #
#                                                                              #
# Purpose: find principal idempotents of a Hermitian matrix                    #
#                                                                              #
# Arguments:                                                                   #
#   A        Hermitian sage or numpy matrix     adjacency matrix/Hamiltonian   #
#   k        integer                            rounding accuracy              #
#                                                                              #
# Returns: principal idempotents, eigenvalues                                  #
#                                                                              #
################################################################################
def idempotents(A, k):
    if not matrix(A).is_hermitian():
        print("A is not Hermitian")
        return []
    # Extracts eigenvalues and eigenvectors
    W,V = linalg.eigh(A)
    # Converts eigenvectors into orthonormal basis
    Q, R = linalg.qr(V) 
    Q = matrix(Q)
    # Number of eigenvectors
    A = np.matrix(A)
    n = len(A)
    idems = []
    evals = []
    i = 0
    j = 0
    while i < n:
        # Zero matrix
        E = matrix(n, n, 0)
        # Checks if eigenvectors share an eigenvalue
        while j < n and abs(W[i] - W[j]) < 0.01:
            # Converts eigenvector into column vecror
            v = Q.column(j).column()
            # updates idempotent
            E = E + v*v.transpose();
            j = j + 1
        E = E.round(k)
        idems.append(E)
        evals.append(W[i].round(k))
        i = j
    return idems, evals

In [2]:
################################################################################
# Function: transfer                                                           #
#                                                                              #
# Purpose: return transfer matrix U(t) given adjacency matrix/Hamiltonian      #
#                                                                              #
# Arguments:                                                                   #
#   A        Hermitian sage or numpy matrix     adjacency matrix/Hamiltonian   #
#   t        float                              time                           #
#   k        integer                            rounding accuracy              #
#                                                                              #
# Returns: transfer U(t)                                                       #
#                                                                              #
################################################################################

def transfer(A, t, k):
    if not A.is_hermitian():
        print("A is not Hermitian")
        return []
    idems, evals = idempotents(A,5)
    n = A.nrows()
    U = matrix(n, n, 0)
    for i in range(len(idems)):
        U = U + exp(I*t*evals[i])*idems[i]
    return U.round(k)      

In [3]:
# Example usages
AC6 = matrix([[0,0,1,0,0,1],[0,0,0,1,1,0],[1,0,0,0,1,0],[0,1,0,0,0,1],[0,1,1,0,0,0],[1,0,0,1,0,0]])
idempotents(AC6, 5)

([
[ 0.16667 -0.16667 -0.16667  0.16667  0.16667 -0.16667]
[-0.16667  0.16667  0.16667 -0.16667 -0.16667  0.16667]
[-0.16667  0.16667  0.16667 -0.16667 -0.16667  0.16667]
[ 0.16667 -0.16667 -0.16667  0.16667  0.16667 -0.16667]
[ 0.16667 -0.16667 -0.16667  0.16667  0.16667 -0.16667]
[-0.16667  0.16667  0.16667 -0.16667 -0.16667  0.16667],

[ 0.33333  0.33333 -0.16667 -0.16667 -0.16667 -0.16667]
[ 0.33333  0.33333 -0.16667 -0.16667 -0.16667 -0.16667]
[-0.16667 -0.16667  0.33333  0.33333 -0.16667 -0.16667]
[-0.16667 -0.16667  0.33333  0.33333 -0.16667 -0.16667]
[-0.16667 -0.16667 -0.16667 -0.16667  0.33333  0.33333]
[-0.16667 -0.16667 -0.16667 -0.16667  0.33333  0.33333],

[ 0.33333 -0.33333  0.16667 -0.16667 -0.16667  0.16667]
[-0.33333  0.33333 -0.16667  0.16667  0.16667 -0.16667]
[ 0.16667 -0.16667  0.33333 -0.33333  0.16667 -0.16667]
[-0.16667  0.16667 -0.33333  0.33333 -0.16667  0.16667]
[-0.16667  0.16667  0.16667 -0.16667  0.33333 -0.33333]
[ 0.16667 -0.16667 -0.16667  0.16667 -0.3

In [4]:
transfer(AC6,np.pi, 5)

[-0.33332      0.0      0.0  0.66668  0.66668      0.0]
[     0.0 -0.33332  0.66668      0.0      0.0  0.66668]
[     0.0  0.66668 -0.33332      0.0      0.0  0.66668]
[ 0.66668      0.0      0.0 -0.33332  0.66668      0.0]
[ 0.66668      0.0      0.0  0.66668 -0.33332      0.0]
[     0.0  0.66668  0.66668      0.0      0.0 -0.33332]

In [5]:
AC5 = matrix([[0,1,0,0,1],[1,0,1,0,0],[0,1,0,1,0],[0,0,1,0,1],[1,0,0,1,0]]); AC5

[0 1 0 0 1]
[1 0 1 0 0]
[0 1 0 1 0]
[0 0 1 0 1]
[1 0 0 1 0]

In [6]:
transfer(AC5,np.pi, 5)

[    0.2 + 0.74563*I 0.03794 - 0.18641*I 0.36206 - 0.18641*I 0.36206 - 0.18641*I 0.03794 - 0.18641*I]
[0.03794 - 0.18641*I     0.2 + 0.74563*I 0.03794 - 0.18641*I 0.36206 - 0.18641*I 0.36206 - 0.18641*I]
[0.36206 - 0.18641*I 0.03794 - 0.18641*I     0.2 + 0.74563*I 0.03794 - 0.18641*I 0.36206 - 0.18641*I]
[0.36206 - 0.18641*I 0.36206 - 0.18641*I 0.03794 - 0.18641*I     0.2 + 0.74563*I 0.03794 - 0.18641*I]
[0.03794 - 0.18641*I 0.36206 - 0.18641*I 0.36206 - 0.18641*I 0.03794 - 0.18641*I     0.2 + 0.74563*I]

In [7]:
AC4 = matrix([[0, 0, 1, 1],[0, 0, 1, 1],[1, 1, 0, 0],[1, 1, 0, 0]]); AC4

[0 0 1 1]
[0 0 1 1]
[1 1 0 0]
[1 1 0 0]

In [8]:
idempotents(AC4,5)

([
[ 0.25  0.25 -0.25 -0.25]  [ 0.5 -0.5 -0.0 -0.0]
[ 0.25  0.25 -0.25 -0.25]  [-0.5  0.5  0.0 -0.0]
[-0.25 -0.25  0.25  0.25]  [-0.0  0.0  0.5 -0.5]
[-0.25 -0.25  0.25  0.25], [-0.0 -0.0 -0.5  0.5],

[0.25 0.25 0.25 0.25]
[0.25 0.25 0.25 0.25]
[0.25 0.25 0.25 0.25]
[0.25 0.25 0.25 0.25]
],
 [-2.0, -0.0, 2.0])

In [9]:
H = np.matrix([[0,1j],[-1j,0]])

In [10]:
res1, res2 = idempotents(H,5); res1

[
[  0.5 0.5*I]  [   0.5 -0.5*I]
[0.5*I  -0.5], [-0.5*I   -0.5]
]