In [126]:
import numpy as np
from numpy import linalg

# Function accepts an adjacency matrix of a graph and returns its idempotents
def idempotents_2(A):
    if not A.is_hermitian():
        print("A is not Hermitian")
        return []
    # Extracts eigenvalues and eigenvectors
    W,V = linalg.eigh(A)
    # Converts eigenvectors into orthonormal basis
    Q, R = linalg.qr(V) 
    Q = matrix(Q)
    # Number of eigenvectors
    n = A.nrows()
    idems = []
    evals = []
    i = 0
    j = 0
    while i < n:
        # Zero matrix
        E = matrix(n, n, 0)
        # Checks if eigenvectors share an eigenvalue
        while j < n and abs(W[i] - W[j]) < 0.01:
            # Converts eigenvector into column vecror
            v = Q.column(j).column()
            # updates idempotent
            E = E + v*v.transpose();
            j = j + 1
        E = E.round(5)
        idems.append(E)
        evals.append(W[i])
        i = j
    return idems, evals

In [127]:
# Example usage
AC6 = matrix([[0,0,1,0,0,1],[0,0,0,1,1,0],[1,0,0,0,1,0],[0,1,0,0,0,1],[0,1,1,0,0,0],[1,0,0,1,0,0]])
idempotents_2(AC6)

([
[ 0.16667 -0.16667 -0.16667  0.16667  0.16667 -0.16667]
[-0.16667  0.16667  0.16667 -0.16667 -0.16667  0.16667]
[-0.16667  0.16667  0.16667 -0.16667 -0.16667  0.16667]
[ 0.16667 -0.16667 -0.16667  0.16667  0.16667 -0.16667]
[ 0.16667 -0.16667 -0.16667  0.16667  0.16667 -0.16667]
[-0.16667  0.16667  0.16667 -0.16667 -0.16667  0.16667],

[ 0.33333  0.33333 -0.16667 -0.16667 -0.16667 -0.16667]
[ 0.33333  0.33333 -0.16667 -0.16667 -0.16667 -0.16667]
[-0.16667 -0.16667  0.33333  0.33333 -0.16667 -0.16667]
[-0.16667 -0.16667  0.33333  0.33333 -0.16667 -0.16667]
[-0.16667 -0.16667 -0.16667 -0.16667  0.33333  0.33333]
[-0.16667 -0.16667 -0.16667 -0.16667  0.33333  0.33333],

[ 0.33333 -0.33333  0.16667 -0.16667 -0.16667  0.16667]
[-0.33333  0.33333 -0.16667  0.16667  0.16667 -0.16667]
[ 0.16667 -0.16667  0.33333 -0.33333  0.16667 -0.16667]
[-0.16667  0.16667 -0.33333  0.33333 -0.16667  0.16667]
[-0.16667  0.16667  0.16667 -0.16667  0.33333 -0.33333]
[ 0.16667 -0.16667 -0.16667  0.16667 -0.3

In [136]:
def transfer(A, t, k):
    if not A.is_hermitian():
        print("A is not Hermitian")
        return []
    idems, evals = idempotents_2(A)
    n = A.nrows()
    U = matrix(n, n, 0)
    for i in range(len(idems)):
        U = U + exp(I*t*evals[i])*idems[i]
    return U.round(k)      

In [140]:
transfer(AC6,np.pi, 5)

[-0.33332      0.0      0.0  0.66668  0.66668      0.0]
[     0.0 -0.33332  0.66668      0.0      0.0  0.66668]
[     0.0  0.66668 -0.33332      0.0      0.0  0.66668]
[ 0.66668      0.0      0.0 -0.33332  0.66668      0.0]
[ 0.66668      0.0      0.0  0.66668 -0.33332      0.0]
[     0.0  0.66668  0.66668      0.0      0.0 -0.33332]

In [138]:
AC5 = matrix([[0,1,0,0,1],[1,0,1,0,0],[0,1,0,1,0],[0,0,1,0,1],[1,0,0,1,0]]); AC5

[0 1 0 0 1]
[1 0 1 0 0]
[0 1 0 1 0]
[0 0 1 0 1]
[1 0 0 1 0]

In [141]:
transfer(AC5,np.pi, 5)

[    0.2 + 0.74563*I 0.03794 - 0.18641*I 0.36206 - 0.18641*I 0.36206 - 0.18641*I 0.03794 - 0.18641*I]
[0.03794 - 0.18641*I     0.2 + 0.74563*I 0.03794 - 0.18641*I 0.36206 - 0.18641*I 0.36206 - 0.18641*I]
[0.36206 - 0.18641*I 0.03794 - 0.18641*I     0.2 + 0.74563*I 0.03794 - 0.18641*I 0.36206 - 0.18641*I]
[0.36206 - 0.18641*I 0.36206 - 0.18641*I 0.03794 - 0.18641*I     0.2 + 0.74563*I 0.03794 - 0.18641*I]
[0.03794 - 0.18641*I 0.36206 - 0.18641*I 0.36206 - 0.18641*I 0.03794 - 0.18641*I     0.2 + 0.74563*I]

In [ ]:
AC4 = matrix